version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Путь к конфигурации для проксирования
    depends_on:
      - backend
    networks:
      - dev
    
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '200209318Dak()'
      MYSQL_DATABASE: 'papa_task'
      MYSQL_USER: 'dak'
      MYSQL_PASSWORD: '200209318Dak()'
    ports:
      - "127.0.0.1:3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - dev

  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - dev
    depends_on:
      - db
    env_file:
      - .env
    

  frontend:
    build: ./frontend
    ports:
      - "192.168.88.18:8001:8001"
    networks:
      - dev

networks:
  dev:
    driver: bridge

volumes:
  mysql-data:
